package by.news.management.controller;

public enum CommandName {
	SIGN_IN,SIGN_OUT,REGISTRATION,CREATE_NEWS,EDIT_NEWS,DELETE_NEWS,SHOW_NEWS_VIEW,SHOW_NEWS_LIST, SAVE_NEWS, ERROR_REGISTRATION, ERROR_AUTH, SHOW_REGISTRATION_PAGE, SHOW_AUTH_PAGE,LOCAL,SHOW_EDIT_NEWS,SHOW_ERROR
}
